services:
  - type: web
    name: pokex1
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k eventlet -w 1 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
